- name: "download pre-build binaries lighhouse"
  ansible.builtin.unarchive:
    src: "{{ lth_releasei_url }}"
    dest: "{{ eth_root }}/bin"
    remote_src: yes
  become: true
  become_user: "{{ eth_user_name }}"
